# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\tservicepb\"!\n\x10SendTopicRequest\x12\r\n\x05topic\x18\x01 \x01(\t\"F\n\x11SendTopicResponse\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\x0f\n\x07\x63\x61ption\x18\x02 \x01(\t\x12\x11\n\tmime_type\x18\x03 \x01(\t2`\n\x16\x41IMemeGeneratorService\x12\x46\n\tSendTopic\x12\x1b.servicepb.SendTopicRequest\x1a\x1c.servicepb.SendTopicResponseBCZAhttps://github.com/ManoVikram/AI-Meme-Generator/backend/api/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZAhttps://github.com/ManoVikram/AI-Meme-Generator/backend/api/proto'
  _globals['_SENDTOPICREQUEST']._serialized_start=28
  _globals['_SENDTOPICREQUEST']._serialized_end=61
  _globals['_SENDTOPICRESPONSE']._serialized_start=63
  _globals['_SENDTOPICRESPONSE']._serialized_end=133
  _globals['_AIMEMEGENERATORSERVICE']._serialized_start=135
  _globals['_AIMEMEGENERATORSERVICE']._serialized_end=231
# @@protoc_insertion_point(module_scope)
