// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AIMemeGeneratorService_SendTopic_FullMethodName = "/servicepb.AIMemeGeneratorService/SendTopic"
)

// AIMemeGeneratorServiceClient is the client API for AIMemeGeneratorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AIMemeGeneratorServiceClient interface {
	SendTopic(ctx context.Context, in *SendTopicRequest, opts ...grpc.CallOption) (*SendTopicResponse, error)
}

type aIMemeGeneratorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAIMemeGeneratorServiceClient(cc grpc.ClientConnInterface) AIMemeGeneratorServiceClient {
	return &aIMemeGeneratorServiceClient{cc}
}

func (c *aIMemeGeneratorServiceClient) SendTopic(ctx context.Context, in *SendTopicRequest, opts ...grpc.CallOption) (*SendTopicResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendTopicResponse)
	err := c.cc.Invoke(ctx, AIMemeGeneratorService_SendTopic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AIMemeGeneratorServiceServer is the server API for AIMemeGeneratorService service.
// All implementations must embed UnimplementedAIMemeGeneratorServiceServer
// for forward compatibility.
type AIMemeGeneratorServiceServer interface {
	SendTopic(context.Context, *SendTopicRequest) (*SendTopicResponse, error)
	mustEmbedUnimplementedAIMemeGeneratorServiceServer()
}

// UnimplementedAIMemeGeneratorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAIMemeGeneratorServiceServer struct{}

func (UnimplementedAIMemeGeneratorServiceServer) SendTopic(context.Context, *SendTopicRequest) (*SendTopicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendTopic not implemented")
}
func (UnimplementedAIMemeGeneratorServiceServer) mustEmbedUnimplementedAIMemeGeneratorServiceServer() {
}
func (UnimplementedAIMemeGeneratorServiceServer) testEmbeddedByValue() {}

// UnsafeAIMemeGeneratorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AIMemeGeneratorServiceServer will
// result in compilation errors.
type UnsafeAIMemeGeneratorServiceServer interface {
	mustEmbedUnimplementedAIMemeGeneratorServiceServer()
}

func RegisterAIMemeGeneratorServiceServer(s grpc.ServiceRegistrar, srv AIMemeGeneratorServiceServer) {
	// If the following call pancis, it indicates UnimplementedAIMemeGeneratorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AIMemeGeneratorService_ServiceDesc, srv)
}

func _AIMemeGeneratorService_SendTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendTopicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIMemeGeneratorServiceServer).SendTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIMemeGeneratorService_SendTopic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIMemeGeneratorServiceServer).SendTopic(ctx, req.(*SendTopicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AIMemeGeneratorService_ServiceDesc is the grpc.ServiceDesc for AIMemeGeneratorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AIMemeGeneratorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "servicepb.AIMemeGeneratorService",
	HandlerType: (*AIMemeGeneratorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendTopic",
			Handler:    _AIMemeGeneratorService_SendTopic_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
