// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateMemeWithTopicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateMemeWithTopicRequest) Reset() {
	*x = GenerateMemeWithTopicRequest{}
	mi := &file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateMemeWithTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateMemeWithTopicRequest) ProtoMessage() {}

func (x *GenerateMemeWithTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateMemeWithTopicRequest.ProtoReflect.Descriptor instead.
func (*GenerateMemeWithTopicRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateMemeWithTopicRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type GenerateMemeWithTopicResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         string                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Caption       string                 `protobuf:"bytes,2,opt,name=caption,proto3" json:"caption,omitempty"`
	MimeType      string                 `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateMemeWithTopicResponse) Reset() {
	*x = GenerateMemeWithTopicResponse{}
	mi := &file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateMemeWithTopicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateMemeWithTopicResponse) ProtoMessage() {}

func (x *GenerateMemeWithTopicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateMemeWithTopicResponse.ProtoReflect.Descriptor instead.
func (*GenerateMemeWithTopicResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateMemeWithTopicResponse) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *GenerateMemeWithTopicResponse) GetCaption() string {
	if x != nil {
		return x.Caption
	}
	return ""
}

func (x *GenerateMemeWithTopicResponse) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\tservicepb\"4\n" +
	"\x1cGenerateMemeWithTopicRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\"l\n" +
	"\x1dGenerateMemeWithTopicResponse\x12\x14\n" +
	"\x05image\x18\x01 \x01(\tR\x05image\x12\x18\n" +
	"\acaption\x18\x02 \x01(\tR\acaption\x12\x1b\n" +
	"\tmime_type\x18\x03 \x01(\tR\bmimeType2\x84\x01\n" +
	"\x16AIMemeGeneratorService\x12j\n" +
	"\x15GenerateMemeWithTopic\x12'.servicepb.GenerateMemeWithTopicRequest\x1a(.servicepb.GenerateMemeWithTopicResponseBCZAhttps://github.com/ManoVikram/AI-Meme-Generator/backend/api/protob\x06proto3"

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData []byte
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)))
	})
	return file_service_proto_rawDescData
}

var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_service_proto_goTypes = []any{
	(*GenerateMemeWithTopicRequest)(nil),  // 0: servicepb.GenerateMemeWithTopicRequest
	(*GenerateMemeWithTopicResponse)(nil), // 1: servicepb.GenerateMemeWithTopicResponse
}
var file_service_proto_depIdxs = []int32{
	0, // 0: servicepb.AIMemeGeneratorService.GenerateMemeWithTopic:input_type -> servicepb.GenerateMemeWithTopicRequest
	1, // 1: servicepb.AIMemeGeneratorService.GenerateMemeWithTopic:output_type -> servicepb.GenerateMemeWithTopicResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
